--Proyecto Final - Base de Datos
--Grupo 9
/****************************************************************************************************************************************************************
***                                                                        TABLESPACE                                                                         ***
****************************************************************************************************************************************************************/
--Creacion de Tablespace
CREATE TABLESPACE ReservasTS
DATAFILE 'reservas_ts.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 50M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE PedidosTS
DATAFILE 'pedidos_ts.dbf'
SIZE 100M
AUTOEXTEND ON
NEXT 50M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


/****************************************************************************************************************************************************************
***                                                                    USUARIOS Y ROLES                                                                       ***
****************************************************************************************************************************************************************/
-- Creacion de Usuarios y Roles
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER reservadb_user IDENTIFIED BY 12345
DEFAULT TABLESPACE ReservasTS
QUOTA UNLIMITED ON ReservasTS;

CREATE ROLE reservas_role;

GRANT CONNECT, RESOURCE TO reservas_role;

GRANT reservas_role TO reservadb_user;


/****************************************************************************************************************************************************************
***                                                                          TABLAS                                                                           ***
****************************************************************************************************************************************************************/

-- Creacion de la tabla: Cliente
CREATE TABLE CLIENTE (
    CLIENTEID       NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    APELLIDO        VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL UNIQUE,
    TELEFONO        VARCHAR2(20) NOT NULL,
    FECHAREGISTRO   DATE NOT NULL,
    ACTIVO          NUMBER(1) DEFAULT 1 NOT NULL
)
TABLESPACE ReservasTS;


-- Creacion de la tabla: Restaurante
CREATE TABLE RESTAURANTE (
    RESTAURANTEID   NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    DIRECCION       VARCHAR2(255),
    TELEFONO        VARCHAR2(20),
    EMAIL           VARCHAR2(100) UNIQUE,
    ACTIVO          NUMBER(1) DEFAULT 1 NOT NULL
)
TABLESPACE ReservasTS;


-- Creacion de la tabla: Empleado
CREATE TABLE EMPLEADO (
    EMPLEADOID          NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    RESTAURANTEID       NUMBER NOT NULL,
    NOMBRE              VARCHAR2(100) NOT NULL,
    APELLIDO            VARCHAR2(100) NOT NULL,
    CARGO               VARCHAR2(100),
    FECHACONTRATACION   DATE NOT NULL,
    ACTIVO              NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_Empleado_Restaurante FOREIGN KEY (RESTAURANTEID) REFERENCES RESTAURANTE(RESTAURANTEID)
)
TABLESPACE ReservasTS;


-- Creacion de la tabla: Mesa
CREATE TABLE MESA (
    MESAID          NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    RESTAURANTEID   NUMBER NOT NULL,
    NUMEROMESA      NUMBER NOT NULL,
    CAPACIDAD       NUMBER NOT NULL,
    UBICACION       VARCHAR2(100),
    ACTIVO          NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_Mesa_Restaurante FOREIGN KEY (RESTAURANTEID) REFERENCES RESTAURANTE(RESTAURANTEID)
)
TABLESPACE ReservasTS;


-- Creacion de la tabla: Reserva
CREATE TABLE RESERVA (
    RESERVAID       NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    CLIENTEID       NUMBER NOT NULL,
    MESAID          NUMBER NOT NULL,
    NUMEROPERSONAS  NUMBER NOT NULL,
    FECHARESERVA    DATE NOT NULL,
    ESTADO          VARCHAR2(50) DEFAULT 'Pendiente' NOT NULL,
    ACTIVO          NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_Reserva_Cliente FOREIGN KEY (CLIENTEID) REFERENCES CLIENTE(CLIENTEID),
    CONSTRAINT FK_Reserva_Mesa FOREIGN KEY (MESAID) REFERENCES MESA(MESAID)
)
TABLESPACE ReservasTS;


-- Creacion de la tabla: Menu
CREATE TABLE MENU (
    MENUID          NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    DESCRIPCION     VARCHAR2(255),
    PRECIO          NUMBER(10, 2) NOT NULL,
    DISPONIBLE      NUMBER(1) DEFAULT 1
)
TABLESPACE PedidosTS;


-- Creacion de la tabla: Pedido
CREATE TABLE PEDIDO (
    PEDIDOID        NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    RESERVAID       NUMBER NOT NULL,
    FECHAPEDIDO     DATE NOT NULL,
    TOTAL           NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_Pedido_Reserva FOREIGN KEY (RESERVAID) REFERENCES RESERVA(RESERVAID)
)
TABLESPACE PedidosTS;


-- Creacion de la tabla: DetallePedido
CREATE TABLE DETALLEPEDIDO (
    DETALLEPEDIDOID     NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    PEDIDOID            NUMBER NOT NULL,
    MENUID              NUMBER NOT NULL,
    CANTIDAD            NUMBER NOT NULL,
    PRECIO              NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_DetallePedido_Pedido FOREIGN KEY (PEDIDOID) REFERENCES PEDIDO(PEDIDOID),
    CONSTRAINT FK_DetallePedido_Menu FOREIGN KEY (MENUID) REFERENCES MENU(MENUID)
)
TABLESPACE PedidosTS;

-- Drop tablas y tablespaces para hacer modificaciones
/*
SELECT CONSTRAINT_NAME, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE R_CONSTRAINT_NAME IN (
    SELECT CONSTRAINT_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'MESA' AND CONSTRAINT_TYPE = 'P'
) AND CONSTRAINT_TYPE = 'R';

ALTER TABLE RESERVA DROP CONSTRAINT FK_RESERVA_MESA;

DROP TABLE CLIENTE;
DROP TABLE RESTAURANTE;
DROP TABLE EMPLEADO;
DROP TABLE MESA;
DROP TABLE RESERVA;
DROP TABLE MENU;
DROP TABLE PEDIDO;
DROP TABLE DETALLEPEDIDO;
DROP TABLESPACE PedidosTS INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE ReservasTS INCLUDING CONTENTS AND DATAFILES;
DROP USER RESERVADB_USER;
DROP ROLE RESERVAS_ROLE;
*/

/****************************************************************************************************************************************************************
***                                                                          INDICES                                                                          ***
****************************************************************************************************************************************************************/

-- Indice en Pedidos basado en ReservaID
CREATE INDEX IDX_Pedidos_ReservaID
ON Pedido (Reservaid)
TABLESPACE PedidosTS;


-- Indice en DetallePedidos basado en PedidoID y MenuID
CREATE INDEX IDX_DetallePedidos_PedidoID_MenuID
ON DetallePedido (PedidoID, MenuID)
TABLESPACE PedidosTS;


-- Indice en Clientes basado en FechaRegistro
CREATE INDEX IDX_Clientes_FechaRegistro
ON Cliente (FechaRegistro)
TABLESPACE ReservasTS;


-- Politica de Contraseñas
ALTER PROFILE DEFAULT LIMIT
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 90
    PASSWORD_GRACE_TIME 7
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 5
    PASSWORD_VERIFY_FUNCTION VERIFY_FUNCTION_11G;


/****************************************************************************************************************************************************************
***                                                                         INSERTS                                                                           ***
****************************************************************************************************************************************************************/

-- Inserts para la tabla Cliente
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Juan', 'Perez', 'juan.perez@example.com', '1234567890', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Maria', 'Gomez', 'maria.gomez@example.com', '0987654321', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Carlos', 'Rodriguez', 'carlos.rodriguez@example.com', '1122334455', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Fernanda', 'Sanchez', 'fernanda.sanchez@example.com', '9910359349', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Ximena', 'Lopez', 'ximena.lopez@example.com', '6900100939', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Nicolas', 'Ruiz', 'nicolas.ruiz@example.com', '9414387412', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Carlos', 'Moreno', 'carlos.moreno@example.com', '2156405421', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Raquel', 'Ruiz', 'raquel.ruiz@example.com', '8188739858', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Karla', 'Garcia', 'karla.garcia@example.com', '7873703740', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Pablo', 'Martinez', 'pablo.martinez@example.com', '2173075537', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Sofia', 'Diaz', 'sofia.diaz@example.com', '5514000098', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Karla', 'Marin', 'karla.diaz@example.com', '2264008285', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Gabriel', 'Diaz', 'gabriel.diaz@example.com', '2342515130', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Tomas', 'Vazquez', 'tomas.vazquez@example.com', '3090974250', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Maria', 'Rodriguez', 'maria.rodriguez@example.com', '2196790449', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Daniela', 'Martinez', 'daniela.martinez@example.com', '9890846409', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Daniela', 'Gomez', 'daniela.gomez@example.com', '6902234181', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Ximena', 'Ruiz', 'ximena.ruiz@example.com', '6243320504', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Ana', 'Vazquez', 'ana.vazquez@example.com', '2162398471', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Tomas', 'Sanchez', 'tomas.sanchez@example.com', '9955104214', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Eduardo', 'Ramirez', 'eduardo.ramirez@example.com', '4184848412', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Ximena', 'Rivera', 'ximena.rivera@example.com', '8067582733', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Eduardo', 'Vazquez', 'eduardo.vazquez@example.com', '3798086937', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Daniela', 'Rodriguez', 'daniela.rodriguez@example.com', '7769572934', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Isabel', 'Sanchez', 'isabel.sanchez@example.com', '4382758803', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Daniela', 'Castillo', 'daniela.castillo@example.com', '5783743419', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Raquel', 'Alvarez', 'raquel.alvarez@example.com', '9810092495', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Maria', 'Ruiz', 'maria.ruiz@example.com', '8752058322', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Carlos', 'Hernandez', 'carlos.hernandez@example.com', '3127598686', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Raquel', 'Torres', 'raquel.torres@example.com', '3575983466', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Yolanda', 'Gonzalez', 'yolanda.gonzalez@example.com', '4552978310', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Nicolas', 'Garcia', 'nicolas.garcia@example.com', '3970182333', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Valeria', 'Vazquez', 'valeria.vazquez@example.com', '8547520629', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Nicolas', 'Castillo', 'nicolas.castillo@example.com', '5755334772', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Yolanda', 'Lopez', 'yolanda.lopez@example.com', '3649196040', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Yolanda', 'Perez', 'yolanda.perez@example.com', '1287095335', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Nicolas', 'Gomez', 'nicolas.gomez@example.com', '1656719777', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Ana', 'Sanchez', 'ana.sanchez@example.com', '5419317509', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Paula', 'Garcia', 'ana.garcia@example.com', '5719766411', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Luis', 'Torres', 'luis.torres@example.com', '5634200746', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Raquel', 'Gomez', 'raquel.gomez@example.com', '4650855056', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Horacio', 'Villalobos', 'ximena.castillo@example.com', '2586356308', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Nicolas', 'Rodriguez', 'nicolas.rodriguez@example.com', '3353559961', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Sofia', 'Jimenez', 'sofia.jimenez@example.com', '9298907996', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Eduardo', 'Ruiz', 'eduardo.ruiz@example.com', '3726624744', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Valeria', 'Sanchez', 'valeria.sanchez@example.com', '1290258803', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Martin', 'Gutierrez', 'martin.gutierrez@example.com', '9218790595', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Josefina', 'Rojas', 'josefina.rojas@example.com', '6328714734', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Martina', 'Piedra', 'martina.pieda@example.com', '3980594385', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Armando', 'Monge', 'armando.monge@example.com', '7546345466', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Patricia', 'Torres', 'patricia.torres@example.com', '1298459534', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Victoria', 'Castillo', 'victoria.castillo@example.com', '2278545401', SYSDATE);
INSERT INTO CLIENTE (NOMBRE, APELLIDO, EMAIL, TELEFONO, FECHAREGISTRO) VALUES ('Natalia', 'Villalobos', 'natalia.villalobos@example.com', '9273278547', SYSDATE);

-- Inserts para la tabla Restaurante
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante El Sabor', 'Calle Falsa 123, Ciudad A', '22223333', 'contacto@sabor.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Gourmet', 'Avenida Principal 456, Ciudad A', '33334444', 'info@gourmet.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Sabor Latino', 'Calle Falsa 456, Ciudad B', '11110000', 'contacto@saborlatino.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Amanecer Tropico', 'Avenida Principal 123, Ciudad B', '44441111', 'info@amatro.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Oliva y Romero', 'Calle Falsa 789, Ciudad C', '44442222', 'contacto@olvrom.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Mar y Tierra', 'Avenida 789, Ciudad C', '99994444', 'info@martierra.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Casa del Rio', 'Calle Falsa 159, Ciudad D', '55556666', 'contacto@casadelrio.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Delicias Urbanas', 'Avenida Principal 268, Ciudad D', '33337777', 'info@deliurb.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Esquina Gourmet', 'Calle Falsa 268, Ciudad X', '99991111', 'contacto@esqgourmet.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Brisas Mediterráneas', 'Avenida Principal 159, Ciudad X', '77772222', 'info@brisasmed.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Jardín Secreto', 'Calle Falsa 908, Ciudad Y', '88880000', 'contacto@jardinsecreto.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Sol y Sombra', 'Avenida Principal 102, Ciudad Y', '55553333', 'info@solsombra.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Rincon Tranquilo', 'Calle Falsa 102, Ciudad Z', '44449999', 'contacto@rtranquilo.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Encanto Natural', 'Avenida Principal 908, Ciudad Z', '22220000', 'info@encantonat.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante El Cebollin', 'Calle Falsa 714, Ciudad U', '33334444', 'contacto@elcebollin.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Ventana del Valle', 'Avenida Principal 622, Ciudad U', '55551111', 'info@vdelv.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Sazón de Abuela Maria', 'Calle Falsa 622, Ciudad V', '99998888', 'contacto@abuelamaria.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Huellas Andinas', 'Avenida Principal 714, Ciudad V', '88882222', 'info@handinas.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante Canto del Chef', 'Calle Falsa 440, Ciudad W', '33336666', 'contacto@callefalsa.com');
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, TELEFONO, EMAIL) VALUES ('Restaurante El Rincón de Lupita', 'Avenida Principal 371, Ciudad W', '44447777', 'info@rinconlupita.com');

-- Inserts para la tabla Empleado
-- Gerentes
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (1, 'Pedro', 'Lopez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Raquel', 'Ruiz', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (3, 'Sofia', 'Diaz', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (4, 'Gabriel', 'Diaz', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (5, 'Maria', 'Rodriguez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Eduardo', 'Ramirez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (7, 'Nataly', 'Rivera', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (8, 'Isabel', 'Sanchez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (9, 'Carlos', 'Hernandez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (10, 'Karla', 'Diaz', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (11, 'Valeria', 'Vazquez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (12, 'Yolanda', 'Perez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (13, 'Ximena', 'Castillo', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (14, 'Martin', 'Gutierrez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (15, 'Armando', 'Monge', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (16, 'Patricia', 'Torres', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (17, 'Alina', 'Jones', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (18, 'Karen', 'Torres', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (19, 'Gloriana', 'Gomez', 'Gerente', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (20, 'Monica', 'Lizano', 'Gerente', SYSDATE);
-- Cocineros
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (1, 'Ana', 'Fernandez', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Fernanda', 'Sanchez', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (3, 'Karla', 'Diaz', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (4, 'Rocio', 'Garcia', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (5, 'Daniela', 'Alfaro', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Ana', 'Vazquez', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (7, 'Patricia', 'Arce', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (8, 'Nicolas', 'Rodriguez', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (9, 'Valeria', 'Sanchez', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (10, 'Victoria', 'Castillo', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (11, 'Martina', 'Rojas', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (12, 'Alberto', 'Sanchez', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (13, 'Karen', 'Monge', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (14, 'Karla', 'Rivera', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (15, 'Daniel', 'Montes', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (16, 'Esteban', 'Diaz', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (17, 'Pedro', 'Campos', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (18, 'Carlos', 'Rodriguez', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (19, 'Valeria', 'Benavides', 'Cocinero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (20, 'Erick', 'Villalobos', 'Cocinero', SYSDATE);
-- Meseros
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (1, 'Nicolas', 'Salazar', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (1, 'Eduardo', 'Vazquez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Tomas', 'Chaves', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Daniela', 'Martinez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (3, 'Luis', 'Ramirez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (3, 'Maria', 'Ruiz', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (3, 'Nicolas', 'Quiros', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (4, 'Luis', 'Torres', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (5, 'Ximena', 'Vega', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (5, 'Marta', 'Diaz', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Pablo', 'Lopez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Jaime', 'Gomez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (7, 'Yolanda', 'Gonzalez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (7, 'Jairo', 'Morera', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (8, 'Manuel', 'Marin', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (8, 'Ligia', 'Lopez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (9, 'Mario', 'Garcia', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (9, 'Raquel', 'Alvarez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (9, 'Eduardo', 'Ruiz', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (10, 'Martina', 'Piedra', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (11, 'Pedro', 'Lopez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (11, 'Roberto', 'Ruiz', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (12, 'Sofia', 'Camacho', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (12, 'Gabriel', 'Diaz', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (13, 'Alejandro', 'Navarro', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (13, 'Maribel', 'Ramirez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (14, 'Luisa', 'Rivera', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (14, 'Mauricio', 'Sanchez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (15, 'Luis', 'Hernandez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (15, 'Marcos', 'Diaz', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (15, 'Valeria', 'Quiros', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (16, 'Fabian', 'Perez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (16, 'Andres', 'Castillo', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (17, 'Francela', 'Gutierrez', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (18, 'Veronica', 'Monge', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (18, 'Patricia', 'Torres', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (19, 'Paula', 'Porras', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (20, 'Natalia', 'Valverde', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (20, 'Sara', 'Marin', 'Mesero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (20, 'Kenneth', 'Lizano', 'Mesero', SYSDATE);
-- Hosts
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Jimena', 'Lopez', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (4, 'Daniela', 'Gomez', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Yolanda', 'Gonzalez', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (8, 'Andrea', 'Solorzano', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (10, 'Nicolas', 'Garcia', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (12, 'Alejandra', 'Ugalde', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (14, 'Ana', 'Garcia', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (16, 'Raquel', 'Alvarez', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (18, 'Eduardo', 'Ruiz', 'Host', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (19, 'Christian', 'Vargas', 'Host', SYSDATE);
-- Cajeros
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (1, 'Roy', 'Ruiz', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Jason', 'Camacho', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (3, 'Carlos', 'Ugalde', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (4, 'Ana', 'Sanchez', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (5, 'Stephanie', 'Valverde', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Marie', 'Rodriguez', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (7, 'Jaime', 'Solorzano', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (8, 'Roberto', 'Chaves', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (9, 'Mauricio', 'Moreno', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (10, 'Ana', 'Sanchez', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (11, 'Rocio', 'Rodriguez', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (12, 'Irene', 'Benavides', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (13, 'Raquel', 'Navarro', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (14, 'Valeria', 'Rojas', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (15, 'Carlos', 'Moreno', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (16, 'Julio', 'Villalobos', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (17, 'Jimena', 'Valverde', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (18, 'Manuel', 'Solorzano', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (19, 'Esteban', 'Monge', 'Cajero', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (20, 'Armando', 'Porras', 'Cajero', SYSDATE);
-- Bartenders
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (1, 'Ericka', 'Ruiz', 'Bartender', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Raquel', 'Alvarez', 'Bartender', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (19, 'Fernanda', 'Villalobos', 'Bartender', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (4, 'Jairo', 'Monge', 'Bartender', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (15, 'Kenneth', 'Alfaro', 'Bartender', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Horacio', 'Campos', 'Bartender', SYSDATE);
-- Ayudantes de cocina
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (1, 'Rocio', 'Rodriguez', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (2, 'Irene', 'Torres', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (3, 'Raquel', 'Vargas', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (4, 'Josefina', 'Rojas', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (5, 'Carlos', 'Moreno', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (6, 'Julio', 'Martinez', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (7, 'Maria', 'Valverde', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (8, 'Manuel', 'Solorzano', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (9, 'Esteban', 'Quiros', 'Ayudante de cocina', SYSDATE);
INSERT INTO EMPLEADO (RESTAURANTEID, NOMBRE, APELLIDO, CARGO, FECHACONTRATACION) VALUES (10, 'Armando', 'Alfaro', 'Ayudante de cocina', SYSDATE);

-- Inserts para la tabla Mesa
-- Restaurante 1
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (1, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (1, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (1, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (1, 4, 6, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (1, 5, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (1, 6, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (1, 7, 2, 'VIP');
-- Restaurante 2
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (2, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (2, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (2, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (2, 4, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (2, 5, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (2, 6, 4, 'Terraza');
-- Restaurante 3
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (3, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (3, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (3, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (3, 4, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (3, 5, 4, 'Terraza');
-- Restaurante 4
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (4, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (4, 2, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (4, 3, 4, 'Terraza');
-- Restaurante 5
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (5, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (5, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (5, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (5, 4, 6, 'Planta Baja');
-- Restaurante 6
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (6, 1, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (6, 2, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (6, 3, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (6, 4, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (6, 5, 4, 'Terraza');
-- Restaurante 7
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (7, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (7, 2, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (7, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (7, 4, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (7, 7, 4, 'VIP');
-- Restaurante 8
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (8, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (8, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (8, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (8, 4, 6, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (8, 5, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (8, 6, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (8, 7, 2, 'VIP');
-- Restaurante 9
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (9, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (9, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (9, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (9, 4, 6, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (9, 4, 4, 'Planta Alta');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (9, 4, 4, 'Planta Alta');
-- Restaurante 10
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (10, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (10, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (10, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (10, 4, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (10, 5, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (10, 7, 2, 'VIP');
-- Restaurante 11
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (11, 1, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (11, 2, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (11, 3, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (11, 4, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (11, 5, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (11, 6, 2, 'VIP');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (11, 7, 4, 'VIP');
-- Restaurante 12
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (12, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (12, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (12, 3, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (12, 4, 4, 'Terraza');
-- Restaurante 13
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (13, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (13, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (13, 3, 4, 'Planta Alta');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (13, 4, 6, 'Planta Alta');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (13, 5, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (13, 6, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (13, 7, 2, 'VIP');
-- Restaurante 14
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (14, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (14, 2, 4, 'Planta Alta');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (14, 3, 4, 'Planta Alta');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (14, 4, 6, 'Planta Alta');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (14, 5, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (14, 6, 4, 'Terraza');
-- Restaurante 15
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (15, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (15, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (15, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (15, 4, 6, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (15, 5, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (15, 6, 2, 'Terraza');
-- Restaurante 16
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (16, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (16, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (16, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (16, 4, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (16, 5, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (16, 6, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (16, 7, 2, 'VIP');
-- Restaurante 17
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (17, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (17, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (17, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (17, 4, 6, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (17, 5, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (17, 6, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (17, 7, 6, 'VIP');
-- Restaurante 18
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (18, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (18, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (18, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (18, 5, 2, 'Terraza');
-- Restaurante 19
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (19, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (19, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (19, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (19, 4, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (19, 5, 2, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (19, 6, 2, 'Terraza');
-- Restaurante 20
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (20, 1, 2, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (20, 2, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (20, 3, 4, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (20, 4, 6, 'Planta Baja');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (20, 5, 6, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (20, 6, 4, 'Terraza');
INSERT INTO MESA (RESTAURANTEID, NUMEROMESA, CAPACIDAD, UBICACION) VALUES (20, 7, 2, 'VIP');

-- Inserts para la tabla Menu (faltan más)
INSERT INTO MENU (NOMBRE, DESCRIPCION, PRECIO) VALUES ('Pizza Margherita', 'Pizza clasica italiana con tomate, mozzarella y albahaca', 12.50);
INSERT INTO MENU (NOMBRE, DESCRIPCION, PRECIO) VALUES ('Ensalada Cesar', 'Ensalada con pollo, lechuga romana, crutones y aderezo Cesar', 8.90);
INSERT INTO MENU (NOMBRE, DESCRIPCION, PRECIO) VALUES ('Tiramisu', 'Postre italiano hecho con cafe, queso mascarpone y cacao', 6.50);


/****************************************************************************************************************************************************************
***                                                                Procedimientos Almacenados                                                                 ***
****************************************************************************************************************************************************************/




/****************************************************************************************************************************************************************
***                                                                     Bloques Anonimos                                                                      ***
****************************************************************************************************************************************************************/
