-- Creaci�n de Tablespaces
 CREATE TABLESPACE ReservasTS DATAFILE 'reservas_ts.dbf' SIZE 50M;
 CREATE TABLESPACE PedidosTS DATAFILE 'pedidos_ts.dbf' SIZE 50M;

-- Tabla Clientes
CREATE TABLE Clientes (
    ClienteID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Apellido VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    Telefono VARCHAR2(20),
    FechaRegistro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Activo NUMBER(1) DEFAULT 1
)
TABLESPACE ReservasTS
;

-- Tabla Mesas
CREATE TABLE Mesas (
    MesaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NumeroMesa NUMBER NOT NULL,
    Capacidad NUMBER NOT NULL,
    Ubicacion VARCHAR2(100)
)
TABLESPACE ReservasTS
;

-- Tabla Reservas
CREATE TABLE Reservas (
    ReservaID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ClienteID NUMBER NOT NULL,
    MesaID NUMBER NOT NULL,
    FechaReserva TIMESTAMP NOT NULL,
    NumeroPersonas NUMBER NOT NULL,
    Estado VARCHAR2(50) DEFAULT 'Pendiente',
    CONSTRAINT FK_Reserva_Cliente FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID),
    CONSTRAINT FK_Reserva_Mesa FOREIGN KEY (MesaID) REFERENCES Mesas(MesaID)
)
TABLESPACE ReservasTS
;

-- Tabla Menus
CREATE TABLE Menus (
    MenuID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Descripcion VARCHAR2(255),
    Precio NUMBER(10, 2) NOT NULL,
    Disponible NUMBER(1) DEFAULT 1
)
TABLESPACE PedidosTS
;

-- Tabla Pedidos
CREATE TABLE Pedidos (
    PedidoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ReservaID NUMBER NOT NULL,
    FechaPedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Total NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_Pedido_Reserva FOREIGN KEY (ReservaID) REFERENCES Reservas(ReservaID)
)
TABLESPACE PedidosTS
;

-- Tabla DetallePedidos
CREATE TABLE DetallePedidos (
    DetallePedidoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PedidoID NUMBER NOT NULL,
    MenuID NUMBER NOT NULL,
    Cantidad NUMBER NOT NULL,
    Precio NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_DetallePedido_Pedido FOREIGN KEY (PedidoID) REFERENCES Pedidos(PedidoID),
    CONSTRAINT FK_DetallePedido_Menu FOREIGN KEY (MenuID) REFERENCES Menus(MenuID)
)
TABLESPACE PedidosTS
;

-- Tabla Empleados
CREATE TABLE Empleados (
    EmpleadoID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Apellido VARCHAR2(100) NOT NULL,
    Cargo VARCHAR2(100),
    FechaContratacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Activo NUMBER(1) DEFAULT 1
)
TABLESPACE ReservasTS
;

-- Tabla Restaurantes
CREATE TABLE Restaurantes (
    RestauranteID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Direccion VARCHAR2(255),
    Telefono VARCHAR2(20),
    Email VARCHAR2(100) UNIQUE
)
TABLESPACE ReservasTS
;

-- �ndice en Reservas basado en FechaReserva
CREATE INDEX IDX_Reservas_FechaReserva
ON Reservas (FechaReserva)
TABLESPACE ReservasTS
;

-- �ndice en Pedidos basado en ReservaID
CREATE INDEX IDX_Pedidos_ReservaID
ON Pedidos (ReservaID)
TABLESPACE PedidosTS
;

-- �ndice en DetallePedidos basado en PedidoID y MenuID
CREATE INDEX IDX_DetallePedidos_PedidoID_MenuID
ON DetallePedidos (PedidoID, MenuID)
TABLESPACE PedidosTS
;

-- �ndice en Clientes basado en FechaRegistro
CREATE INDEX IDX_Clientes_FechaRegistro
ON Clientes (FechaRegistro)
TABLESPACE ReservasTS
;

-- Drop tablas y tablespaces para hacer modificaciones
--DROP TABLE CLIENTES;
--DROP TABLE RESERVAS;
--DROP TABLE MESAS;
--DROP TABLE MENUS;
--DROP TABLE PEDIDOS;
--DROP TABLE DETALLEPEDIDOS;
--DROP TABLE EMPLEADOS;
--DROP TABLE RESTAURANTES;
--DROP TABLESPACE PedidosTS INCLUDING CONTENTS AND DATAFILES;
--DROP TABLESPACE ReservasTS INCLUDING CONTENTS AND DATAFILES;
